# Generated by Django 4.2.7 on 2024-04-14 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.FileField(
                        upload_to="user_files",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "png", "jpg"]
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
